data <-read.table('household_power_consumption.txt',sep=';',header=TRUE)
data$DateTime <- paste(data$Date,data$Time)
data$DateTime <- strptime(as.character(data$DateTime),format = '%d/%m/%Y %H:%M:%S') 
data$Date  = as.Date(strptime(as.character(data$Date),format = '%d/%m/%Y'))
data.filtered <- subset(data, Date >= '2007-02-01' & Date <= '2007-02-02')
data.filtered$Global_active_power <- as.numeric(as.character(data.filtered$Global_active_power))
data.filtered$Sub_metering_1 <- as.numeric(as.character(data.filtered$Sub_metering_1))
data.filtered$Sub_metering_2 <- as.numeric(as.character(data.filtered$Sub_metering_2))
data.filtered$Sub_metering_3 <- as.numeric(as.character(data.filtered$Sub_metering_3))
Sys.setlocale(locale = "C")
png(file = 'plot4.png')
par(mfrow=c(2,2))
plot(data.filtered$DateTime,data.filtered$Global_active_power,type="l",ylab='Global Active Power',xlab='')
data.filtered$Voltage <- as.numeric(as.character(data.filtered$Voltage))
plot(data.filtered$DateTime,data.filtered$Voltage,type="l",ylab='Voltage',xlab='datetime')
plot(data.filtered$DateTime,data.filtered$Sub_metering_1,type="l",xlab = '',ylab = 'Energy sub metering')
lines(data.filtered$DateTime,data.filtered$Sub_metering_2,col='red')
lines(data.filtered$DateTime,data.filtered$Sub_metering_3,col='blue')
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=c(1,1,1),col=c("black","red","blue"),box.lwd=0)
data.filtered$Global_reactive_power<- as.numeric(as.character(data.filtered$Global_reactive_power))
plot(data.filtered$DateTime,data.filtered$Global_reactive_power,type="l",ylab='Global_reactive_power',xlab='datetime')
dev.off()
